#!/bin/sh
#
cd {{pkg.svc_var_path}}

# `exec` makes it so the process that the Habitat supervisor uses is
# `bundle exec server.ruby`, rather than the run hook itself. `2>&1` makes it so both
# standard output and standard error go to the standard output stream,
# so all the logs from the application go to the same place.
exec bundle exec server.rb 2>&1
